In [40]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt

In [41]:
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

Примеры выполнения операций

In [42]:
my_array = np.arange(1000000)
%timeit my_array2 = my_array*2

664 μs ± 27.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [43]:
my_list1 = list(range(1000000))
%timeit my_list2 = [x * 2 for x in my_list1]

21.4 ms ± 351 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


ndarray

In [47]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data.shape
data.dtype


dtype('float64')

Основы работы

In [45]:
array = np.array(["1", "2", "3.5"])
array = array.astype(data.dtype)
array = array.astype(np.int64)
array

array([1, 2, 3])

In [54]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[7, 8, 9], [10, 11, 12]]
    ])
old_values = arr3d[0].copy()
arr3d[0] =  45
print(arr3d[0])
arr3d[0] = old_values
print(arr3d[0])

[[45 45 45]
 [45 45 45]]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1:2, 1:] = 0

array([[1, 2, 3],
       [4, 0, 0],
       [7, 8, 9]])

In [71]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
[-12, -4], [3, 4]])
print("Numpy массив names:\n{}".format(names))
print("Numpy массив data:\n{}".format(data))

Numpy массив names:
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Numpy массив data:
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [88]:
data[names != "Joe", 0]
mask = (names == "Joe") | (names == "Bob")

data[mask]

array([[  4,   7],
       [  0,   2],
       [  0,   0],
       [-12,  -4],
       [  3,   4]])

Прихотливое инджексирование

In [ ]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print("2-мерный Numpy массив arr:\n{}".format(arr))